### ISSUE TITLE
Guns don't work with this mod enabled.

### ISSUE THREAD

**Issue by Geodew** [gamrguy/ItemCustomizer#2]
Guns won't fire or consume ammo. ShaderLib is fine, but enabling this mod as well breaks my guns. They also point at a weird angle when you try to use them. I took a look around: maybe CustomGlobalItem.ConsumeAmmo should return base.ConsumeAmmo instead of True...? I'm not super familiar with tModLoader yet.

**Comment by gamrguy** [comment]
Not reproducible in current version, to my knowledge. Feel free to reopen if this still occurs.
