### ISSUE TITLE
Calamity Mod Issues

### ISSUE THREAD

**Issue by Emblin13** [gamrguy/ItemCustomizer#3]
In multiplayer, when both Calamity and ItemCustomizer are installed, items that change the game's rules like "Revengeance", "Defiled Rune", and "Armageddon" do not work as intended. When activated, they will deactivate themselves just a few seconds later.

[client-1.log](https://github.com/gamrguy/ItemCustomizer/files/4425286/client-1.log)
[server-1.log](https://github.com/gamrguy/ItemCustomizer/files/4425288/server-1.log)

**Comment by gamrguy** [comment]
Not reproducable in current version. Feel free to reopen with new logs if this still occurs.
