### ISSUE TITLE
Support for Terraria Overhaul

### ISSUE THREAD

**Issue by Archilyte** [gamrguy/ItemCustomizer#4]
Would it be possible to make this mod compatible with [Overhaul](https://forums.terraria.org/index.php?threads/terraria-overhaul-gameplay-enhancements-and-much-more.60369/)? If so, can you do it?

**Comment by gamrguy** [comment]
**Terraria Overhaul support is not planned at this time.**

TO does far too many different things. While it is theoretically possible to support TO, there are so many different use cases and variants that it would be impractical to attempt this without intentional integration on Mirsario's part.
